version: '3.8'

services:
  web:
    command: ["python3.8", "manage.py", "runserver", "0.0.0.0:8000"] 
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000