version: '3.8'

services:
  web:
    image: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/ts_app:web
    command: gunicorn django.wsgi:application --bind 0.0.0.0:8000
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2008:2008
      - 3000:3000
    restart: always
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
    volumes:
      - .:/code