version: '3.8'

services:
  web:
    command: gunicorn django.wsgi:application --bind 0.0.0.0:8000 --workers=4
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    restart: always
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
    volumes:
      - .:/code

  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    name: django-network

volumes:
  media_volume:
  static_volume: