version: '3.8'

services:
  ts_app:
    image: ts_app
    container_name: TS_App
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2008:2008
      - 3000:3000
      - 2234:2234
    command: ["python3.8", "manage.py", "runserver", "0.0.0.0:2234"]
    restart: always
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
    volumes:
      - .:/code