version: '3.8'

services:
  ts_app:
    container_name: TS_App
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2008:2008
      - 3000:3000
      - 8080:8080
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
    volumes:
      - .:/code