version: '3.8'

services:
  web:
    command: gunicorn django_settings.wsgi:application --bind 0.0.0.0:8000
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - .:/code
    environment:
      - DEBUG
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - HOST_ENDPOINT

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    name: django-network

volumes:
  media_volume:
  static_volume: