version: '3.8'

services:
  web:
    command: gunicorn django_settings.wsgi:application --bind 0.0.0.0:8000 --timeout 90
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000