branch-defaults:
  main:
    environment: TubeSurfersApp
environment-defaults:
  TubeSurfersApp:
    branch: null
    repository: null
global:
  application_name: TubeSurfersAppPython
  default_ec2_keyname: tube-surfers-ssh
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application