-- MySQL Script generated by MySQL Workbench
-- Mon Jun  6 16:22:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ts_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ts_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ts_db` DEFAULT CHARACTER SET utf8 ;
USE `ts_db` ;

-- -----------------------------------------------------
-- Table `ts_db`.`Timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_db`.`Timestamps` (
  `DBid` INT NOT NULL AUTO_INCREMENT,
  `Timestamp` DECIMAL(11,1) NOT NULL,
  `TubeLine` ENUM('B', 'HSC', 'Cen', 'N', 'Cir', 'WLC', 'J', 'V', 'P', 'M', 'D') NOT NULL,
  `FromStation` ENUM('Euston', 'Euston Road', 'Waterloo', 'West Ham', 'Bromley-by-Bow', 'Bow Road', 'Mile End', 'Stepney Green', 'Whitechapel', 'Aldgate East', 'Tower Hill', 'Monument', 'Cannon Street', 'Mansion House', 'Blackfriars', 'Temple', 'Embankment', 'Westminster', "St James's Park", 'Victoria', 'Sloane Square', 'South Kensington', "Earl's Court", 'West Kensington', 'Ravenscourt Park', 'Stamford Brook', 'Turnham Green', 'Hammersmith', "Baron's Court", 'Gloucester Road', 'Knightsbridge', 'Hyde Park', 'Green Park', 'Piccadilly Circus', 'Leicester Square', 'Covent Garden', 'Holborn', 'Russell Square', "King's Cross St. Pancras", 'Caledonian Road', 'Holloway Road', 'Arsenal', 'Finsbury Park', 'Manor House') NOT NULL,
  `ToStation` ENUM('Euston', 'Euston Road', 'Waterloo', 'West Ham', 'Bromley-by-Bow', 'Bow Road', 'Mile End', 'Stepney Green', 'Whitechapel', 'Aldgate East', 'Tower Hill', 'Monument', 'Cannon Street', 'Mansion House', 'Blackfriars', 'Temple', 'Embankment', 'Westminster', "St James's Park", 'Victoria', 'Sloane Square', 'South Kensington', "Earl's Court", 'West Kensington', 'Ravenscourt Park', 'Stamford Brook', 'Turnham Green', 'Hammersmith', "Baron's Court", 'Gloucester Road', 'Knightsbridge', 'Hyde Park', 'Green Park', 'Piccadilly Circus', 'Leicester Square', 'Covent Garden', 'Holborn', 'Russell Square', "King's Cross St. Pancras", 'Caledonian Road', 'Holloway Road', 'Arsenal', 'Finsbury Park', 'Manor House') NOT NULL,
  `IndexBetweenStations` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`DBid`),
  UNIQUE INDEX `DBid_UNIQUE` (`DBid` ASC),
  UNIQUE INDEX `Timestamp_UNIQUE` (`Timestamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_db`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_db`.`Data` (
  `DBid` INT NOT NULL AUTO_INCREMENT,
  `TimestampID` INT NOT NULL,
  `DataName` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `DataValue` DECIMAL(11,2) NOT NULL,
  `DataType` ENUM('Accelerometer','Sound','Temperature','Pollution','Questionaire') NOT NULL,
  `Units` VARCHAR(10) NULL,
  PRIMARY KEY (`DBid`),
  INDEX `TimestampLink_idx` (`TimestampID` ASC),
  CONSTRAINT `TimestampLink`
    FOREIGN KEY (`TimestampID`)
    REFERENCES `ts_db`.`Timestamps` (`DBid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = Default;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
